server:
  port: 8080

spring:
  application:
    name: author

  profiles:
    active: docker

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: author
          destination: miniprojectjo
          contentType: application/json
        event-out:
          destination: miniprojectjo
          contentType: application/json

api:
  url:
    author: http://author:8080

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
    org.springframework.core.env: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
